["terms"]
CTF = ["collar", "tail fiber", "tail-fiber", "tail_fiber"]
BPL = ["baseplate", "base plate", "base-plate", "base_plate"]
BPO = ["baseplate", "base plate", "base-plate", "base_plate"]
BPA = ["baseplate", "base plate", "base-plate", "base_plate"]
BPU = ["baseplate", "base plate", "base-plate", "base_plate"]
BPM = ["baseplate", "base plate", "base-plate", "base_plate"]
TSP = ["tail spike", "tail-spike", "tailspike", "spike"]
MCP = ["major capsid", "major-capsid", "major_capsid"]
MTL = ["major tail", "major-tail", "major_tail"]
m_CP = ["minor capsid", "minor-capsid", "minor_capsid"]
m_TL = ["minor tail", "minor-tail", "minor_tail"]
PTL = ["portal"]
TSH = ["shaft", "sheath"]
HTJ = [
    "HTJ", 
    "head tail", "head-tail", "head_tail", 
    "head to tail", "head-to-tail", "head_to_tail", 
    "head assembly", "head-assembly", "head_assembly",
    "head completion", "head-completion", "head_completion",
    "head core", "head-core", "head_core",
    ]
PHD = ["phage head", "phage-head", "phage_head"]
