["terms"]
CTF = ["collar", "tail fiber", "tail-fiber"]
BPL = ["baseplate", "base plate"]
TSP = ["tail spike", "tail-spike", "tailspike", "spike"]
MCP = ["major capsid", "major-capsid"]
MTL = ["major tail", "major-tail"]
m_CP = ["minor capsid", "minor-capsid"]
m_TL = ["minor tail", "minor-tail"]
PTL = ["portal"]
TSH = ["shaft", "shaft", "sheath"]
HTJ = ["HTJ", "head-tail", "head tail", "head to tail", "head assembly", "head completion", "head core"]
PHD = ["phage head", "phage-head"]